-- Seed data: existing 6 projects
-- Images reference Vite asset paths (will be updated when R2 is added)

INSERT INTO projects (id, title, location, year, category, description, challenge, approach, scope, result, cover_image, images, sort_order, published)
VALUES
  (
    'commercial-electrical-nairobi',
    'Commercial Electrical Installation',
    'Westlands, Nairobi',
    '2024',
    'Electrical Installation',
    'Complete electrical installation and commissioning for a 12-storey commercial office complex including LV distribution, lighting and fire alarm integration.',
    'The client needed a full electrical fit-out delivered within a tight 16-week programme to meet a tenant occupancy deadline.',
    'We deployed two parallel crews to cover rough-in and first-fix simultaneously, coordinated with the main contractor''s programme and held weekly clashes-detection meetings.',
    '["LV/MV distribution boards and changeover systems","General and emergency lighting installation","Cable containment and trunking","Fire alarm and detection integration","Testing, commissioning and handover certificates"]',
    'All systems tested, certified and handed over two weeks ahead of the occupancy deadline.',
    '/assets/electrical-BAvqOOCp.jpg',
    '["/assets/electrical-BAvqOOCp.jpg"]',
    1,
    1
  ),
  (
    'industrial-solar-athi-river',
    '220kW Industrial Rooftop Solar',
    'Athi River, Machakos',
    '2023',
    'Solar & Renewable Energy',
    'Design, supply and installation of a 220kW grid-tied rooftop solar PV system for a food processing factory.',
    'The factory''s monthly electricity bill exceeded KES 2.5M with no redundancy for power interruptions affecting production lines.',
    'We carried out a detailed energy audit and structural assessment before designing a system that offsets over 40% of daytime consumption.',
    '["Structural assessment and roof preparation","PV module and inverter supply","DC and AC cabling and protection","Grid compliance and net metering application","Remote monitoring and commissioning"]',
    'The system generates an average of 950kWh daily, reducing the client''s monthly electricity spend by approximately 41%.',
    '/assets/solar-C94A-qbw.jpg',
    '["/assets/solar-C94A-qbw.jpg"]',
    2,
    1
  ),
  (
    'fire-detection-mombasa',
    'Fire Detection & Hydrant System',
    'Nyali, Mombasa',
    '2024',
    'Building Services',
    'Design, supply and installation of an addressable fire detection system and wet riser hydrant network for a beachfront hotel.',
    'The county fire department required a fully compliant fire suppression and detection system before issuing the occupancy certificate for the renovated wing.',
    'We installed an addressable fire alarm system with zone mapping and a wet riser hydrant system connected to a dedicated fire pump.',
    '["Addressable fire alarm panel and detectors","Sounder and visual alarm devices","Wet riser and hydrant ring installation","Fire pump supply and commissioning","Emergency lighting and exit signage"]',
    'The system passed county fire department inspection on the first submission, enabling the client to receive occupancy approval without delays.',
    '/assets/fire-BJtBoDX7.jpg',
    '["/assets/fire-BJtBoDX7.jpg"]',
    3,
    1
  ),
  (
    'substation-upgrade-westlands',
    'Substation & LV Distribution Upgrade',
    'Westlands, Nairobi',
    '2023',
    'Power Systems',
    'Upgrade of a 500kVA transformer substation and complete LV distribution reconfiguration for a mixed-use development.',
    'The existing substation was undersized for the expanded development load, causing frequent tripping and power quality issues.',
    'We carried out a load flow analysis, replaced the transformer, reconfigured the LV board and installed power factor correction.',
    '["Transformer replacement and oil test","LV panel reconfiguration and labelling","Power factor correction capacitor bank","Earthing and surge protection upgrade","Testing, commissioning and documentation"]',
    'The upgraded substation handles 35% more capacity with stable power quality and no further tripping incidents.',
    '/assets/electrical-BAvqOOCp.jpg',
    '["/assets/electrical-BAvqOOCp.jpg"]',
    4,
    1
  ),
  (
    'solar-water-heating-nakuru',
    'Solar Water Heating System',
    'Nakuru, Nakuru',
    '2024',
    'Solar & Renewable Energy',
    'Supply and installation of a 600-litre solar water heating system for a 120-bed hospital.',
    'The hospital relied on electric geysers consuming over 18,000 kWh monthly, with unreliable hot water supply during peak demand.',
    'We installed a thermosiphon solar water heating system with electric backup, sized to meet 80% of the facility''s daily hot water demand.',
    '["Solar collector and storage tank installation","Piping and insulation work","Electric backup integration","System commissioning and handover"]',
    'The system provides consistent hot water supply and reduces the hospital''s water heating electricity cost by approximately 65%.',
    '/assets/solar-C94A-qbw.jpg',
    '["/assets/solar-C94A-qbw.jpg"]',
    5,
    1
  ),
  (
    'fire-alarm-system-industrial',
    'Industrial Fire Alarm System',
    'Industrial Area, Nairobi',
    '2023',
    'Building Services',
    'Design and installation of an addressable fire detection and alarm system for a 15,000m² warehouse and logistics facility.',
    'The warehouse stored flammable materials requiring a detection system that could operate across high-bay areas with significant air movement.',
    'We selected beam detectors for the high-bay zones and conventional detectors for offices, integrated with a single addressable panel.',
    '["Fire detection system design and zone mapping","Addressable panel and beam detector installation","Conventional detectors for office areas","Sounder and visual alarm devices","Integration with existing security systems"]',
    'The system was commissioned and certified, meeting all NFPA and county fire department requirements.',
    '/assets/fire-BJtBoDX7.jpg',
    '["/assets/fire-BJtBoDX7.jpg"]',
    6,
    1
  );
